# Generated by Django 4.2.7 on 2024-03-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.CharField(max_length=30, verbose_name='телеграм токен'),
        ),
    ]
