# Generated by Django 4.2.7 on 2024-03-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='time_next_notify',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время следующего оповещения'),
        ),
    ]
