# Generated by Django 4.2.7 on 2024-03-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_start_time_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='start_time_new',
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_next_notify',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время следующего оповещения'),
        ),
    ]
