# Generated by Django 4.2.7 on 2024-03-16 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0013_alter_habit_start_time_alter_habit_time_next_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='time_next_notify',
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 17, 57, 9, 708590), verbose_name='время привычки'),
        ),
    ]
