# Generated by Django 4.2.7 on 2024-03-17 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0014_remove_habit_time_next_notify_alter_habit_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 8, 16, 2, 384328), verbose_name='время привычки'),
        ),
    ]
