# Generated by Django 4.2.7 on 2024-03-17 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0015_alter_habit_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 9, 0, 10, 299132), verbose_name='время привычки'),
        ),
    ]
