# Generated by Django 4.2.7 on 2024-03-17 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0018_alter_habit_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 10, 8, 49, 941289), verbose_name='время привычки'),
        ),
    ]
