# Generated by Django 4.2.7 on 2024-03-17 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0019_alter_habit_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='period_choices',
            new_name='period',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='start_time',
        ),
        migrations.AddField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время привычки'),
        ),
    ]
