# Generated by Django 4.2.7 on 2024-03-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0020_rename_period_choices_habit_period_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
    ]
